{% set name = "ddtrace" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ddtrace-{{ version }}.tar.gz
  sha256: d175d1f3df2b02715aabfce08ab52027abee95f0c844b55bf3398b45e111fcc6

build:
  number: 0
  skip: true  # [python_impl =='pypy']
  entry_points:
    - ddtrace-run = ddtrace.commands.ddtrace_run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make
  host:
    - cython <3
    - python
    - pip
    - setuptools_scm[toml] >=4
  run:
    - psutil >=5.8,<6.dev0
    - typing-extensions
    - wrapt >=1.15,<2.dev0
    - python
    - pip
    - protobuf >=3
    - attrs >=20
    - cattrs
    - six >=1.12.0
    - ddsketch >=2.0.1
    - typing_extensions
    - bytecode
    - xmltodict >=0.12
    - envier
    - opentelemetry-api >=1

test:
  imports:
    - ddtrace
    - ddtrace.bootstrap
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://github.com/DataDog/dd-trace-py
  summary: Datadog APM client library
  license: BSD-3-Clause
  license_file: LICENSE.BSD3

extra:
  recipe-maintainers:
    - aymondebroglie
    - SarvarD
