{% set name = "ddtrace" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ddtrace-{{ version }}.tar.gz
  sha256: 223501c0c7328b56287b60fe520855b87066f6b5ec0543437a46fcc13337f6bc

build:
  number: 0
  skip: true  # [python_impl =='pypy']
  entry_points:
    - ddtrace-run = ddtrace.commands.ddtrace_run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make
  host:
    - cython <3
    - python
    - pip
    - setuptools_scm[toml] >=4
  run:
    - attrs >=20
    - bytecode
    - cattrs
    - ddsketch >=2.0.1
    - envier
    - importlib_metadata  # [py<38]
    - opentelemetry-api >=1
    - protobuf >=3
    - psutil ==5.6.7
    - python
    - setuptools  # [py>=312]
    - six >=1.12.0
    - typing_extensions
    - wrapt ==1.15.0
    - xmltodict >=0.12

test:
  imports:
    - ddtrace
    - ddtrace.bootstrap
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://github.com/DataDog/dd-trace-py
  summary: Datadog APM client library
  license: BSD-3-Clause
  license_file: LICENSE.BSD3

extra:
  recipe-maintainers:
    - aymondebroglie
    - SarvarD
