{% set name = "ddtrace" %}
{% set version = "1.7.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ddtrace-{{ version }}.tar.gz
  sha256: 03bea3cbf585c7ce19395fcb3c52d020ac6ede9f836d5324f303156019e1416c

build:
  number: 0
  skip: true  # [python_impl =='pypy']
  entry_points:
    - ddtrace-run = ddtrace.commands.ddtrace_run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - cython
    - python
    - pip
    - setuptools_scm[toml] >=4,<6.1
  run:
    - python
    - pip
    - protobuf >=3
    - tenacity >=5
    - packaging >=17.1
    - attrs >=20
    - cattrs
    - six >=1.12.0
    - ddsketch >=2.0.1
    - typing_extensions
    - bytecode
    - jsonschema
    - xmltodict >=0.12
    - envier

test:
  imports:
    - ddtrace
    - ddtrace.bootstrap
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://github.com/DataDog/dd-trace-py
  summary: Datadog APM client library
  license: BSD-3-Clause
  license_file: LICENSE.BSD3

extra:
  recipe-maintainers:
    - aymondebroglie
    - SarvarD
