{% set name = "ddtrace" %}
{% set version = "0.59.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ddtrace-{{ version }}.tar.gz
  sha256: bd88b6427bdbbdd813aa3eab887a89b38f88c476f559105eae13f43dccc7052c

build:
  number: 0
  skip: true  # [py==30 or py==31 or py==32 or py==33 or py==34]
  entry_points:
    - ddtrace-run = ddtrace.commands.ddtrace_run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - cmake
    - ninja
    - python
    - pip
    - setuptools_scm[toml] >=4,<6.1
  run:
    - python
    - pip
    - enum34  # [py<34]
    - funcsigs >=1.0.0  # [py==27]
    - typing  # [py<35]
    - protobuf >=3,<3.18  # [py<3.6]
    - protobuf >=3  # [py>=3.6]
    - tenacity >=5
    - packaging >=17.1
    - attrs >=19.2.0
    - six >=1.12.0
    - pep562  # [py<37]

test:
  imports:
    - ddtrace
    - ddtrace.bootstrap
  requires:
    - tox
    - flake8

about:
  home: https://github.com/DataDog/dd-trace-py
  summary: Datadog APM client library
  license: BSD-3-Clause
  license_file: LICENSE.BSD3

extra:
  recipe-maintainers:
    - aymondebroglie
    - SarvarD
