{% set name = "ddtrace" %}
{% set version = "0.52.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ddtrace-{{ version }}.tar.gz
  sha256: bdd953c17c64d09b94178feb8a2af8da14df4e5a535e0bb51269ce3781f6e80a 

build:
  number: 0
  skip: true  # [py==30 or py==31 or py==32 or py==33 or py==34]
  entry_points:
    - ddtrace-run = ddtrace.commands.ddtrace_run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    - setuptools_scm >=4
  run:
    - python
    - pip
    - enum34  # [py<34]
    - funcsigs >=1.0.0  # [py==27]
    - typing  # [py<35]
    - protobuf >=3
    - tenacity >=5
    - packaging >=17.1
    - attrs >=19.2.0
    - six >=1.12.0
    - pep562  # [py<37]

test:
  imports:
    - ddtrace
    - ddtrace.bootstrap
  requires:
    - tox
    - flake8

about:
  home: https://github.com/DataDog/dd-trace-py
  summary: Datadog tracing code
  license: BSD-3-Clause
  license_file: LICENSE.BSD3

extra:
  recipe-maintainers:
    - aymondebroglie
    - SarvarD
