{% set version = "1.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ddtrace-{{ version }}.tar.gz
  sha256: 2af28170116eaec5bd51300fbf6b930224fc074b30dc00d9612db8f0e8294d32

build:
  number: 0
  skip: true  # [python_impl =='pypy']
  entry_points:
    - ddtrace-run = ddtrace.commands.ddtrace_run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - cython
    - python
    - pip
    - setuptools_scm[toml] >=4,<6.1
  run:
    - python
    - pip
    - protobuf >=3
    - tenacity >=5
    - packaging >=17.1
    - attrs >=19.2.0
    - cattrs
    - six >=1.12.0
    - ddsketch >=2.0.1
    - typing_extensions
    - bytecode ~=0.13.0  # [py==37]
    - bytecode  # [py>37]
    - importlib_metadata  # [py<38] 
    - jsonschema
    - xmltodict >=0.12
    - envier

test:
  imports:
    - ddtrace
    - ddtrace.bootstrap
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://github.com/DataDog/dd-trace-py
  summary: Datadog APM client library
  license: BSD-3-Clause
  license_file: LICENSE.BSD3

extra:
  recipe-maintainers:
    - aymondebroglie
    - SarvarD
