{% set name = "ddtrace" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ddtrace-{{ version }}.tar.gz
  sha256: 79d1e2288f9df3fa6001fb3448d7fecb9fa8f5c8497773be4f8cad8fe2e1db08

build:
  number: 0
  entry_points:
    - ddtrace-run = ddtrace.commands.ddtrace_run:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - cython
    - python
    - pip
    - setuptools_scm[toml] >=4,<6.1
  run:
    - python
    - pip
    - protobuf
    - tenacity >=5
    - packaging >=17.1
    - attrs >=19.2.0
    - six >=1.12.0

test:
  imports:
    - ddtrace
    - ddtrace.bootstrap
  requires:
    - tox
    - flake8

about:
  home: https://github.com/DataDog/dd-trace-py
  summary: Datadog APM client library
  license: BSD-3-Clause
  license_file: LICENSE.BSD3

extra:
  recipe-maintainers:
    - aymondebroglie
    - SarvarD
