schema_version: 1

context:
  version: 4.14.0

package:
  name: ddtrace
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/ddtrace/ddtrace-${{ version }}.tar.gz
  sha256: 030699f46e0330b4bfd23bedb94d7a07a588638bed27490851f732f045bf96fe
  patches:
    - patches/001-patch-out-cmake-build-dep.patch
    - patches/002-disable-ddwaf-download.patch

build:
  number: 1
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cd src/native
    - cargo-bundle-licenses --format yaml --output ../../THIRDPARTY.yml
  python:
    entry_points:
      - ddtrace-run = ddtrace.commands.ddtrace_run:main
      - _dd_crashtracker_receiver = ddtrace.commands._dd_crashtracker_receiver:main

requirements:
  build:
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - setuptools-scm >=4
        - setuptools-rust <2
        - setuptools
        - cython
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib("c") }}
    - cmake >=3.24.2,<3.28
    - ninja
    - git
    - make
  host:
    - python
    - setuptools-scm >=4
    - cython
    - cmake >=3.24.2,<3.28
    - setuptools-rust <2
    - setuptools
    - pip
  run:
    - python
    # corresponding to the minimum for py3.14
    - bytecode >=0.17.0,<1
    - envier >=0.6.1,<0.7.dev0
    - opentelemetry-api >=1,<2
    - wrapt >=1,!=2.2.0,<3
    # from unvendoring
    - libddwaf >=2.0,<2.1
tests:
  - python:
      imports:
        - ddtrace
        # test that libddwaf.so is loaded correctly
        - ddtrace.appsec._ddwaf
  - script:
      - ddtrace-run --help

about:
  summary: Datadog APM client library
  license: 0BSD AND Apache-2.0 AND BSD-3-Clause
  homepage: https://github.com/DataDog/dd-trace-py
  documentation: https://ddtrace.readthedocs.io/en/stable/
  license_file:
    - LICENSE
    - LICENSE.BSD3
    - LICENSE.Apache
    - NOTICE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - aymondebroglie
    - SarvarD
    - mgorny
